# version: "3.9"
# services:
#   node:
#     # build: ./utils/gdocs2md/.
#     build: .
#     ports:
#       - "3000:3000"
#     command: ls /node/node_modules
#     volumes:
#       - .:/node
#       - /node/node_modules:/node/node_modules
services:
  node:
    image: hfla-gdocs2md
    container_name: hfla-gdocs2md
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      # https://stackoverflow.com/a/32785014/232619
      - .:/app
      - /app/node_modules
    command: node gdocs2md/scripts/start-express.js
    ports:
      - 3000:3000
